<template>
    <v-text-field
            name="store"
            id="store"
            v-model="location.sl_store"
            v-bind:label="location_manager.text.sl_store"
    ></v-text-field>
    <v-text-field
            name="address"
            id="address"
            v-model="location.sl_address"
            v-bind:label="location_manager.text.sl_address"
            v-bind:hint="location_manager.text.triggers_geocode"
    ></v-text-field>
    <v-text-field
            name="address2"
            id="address2"
            v-model="location.sl_address2"
            v-bind:label="location_manager.text.sl_address2"
            v-bind:hint="location_manager.text.triggers_geocode"
    ></v-text-field>
    <v-text-field
            name="city"
            id="city"
            v-model="location.sl_city"
            v-bind:label="location_manager.text.sl_city"
            v-bind:hint="location_manager.text.triggers_geocode"
    ></v-text-field>
    <v-text-field
            name="state"
            id="state"
            v-model="location.sl_state"
            v-bind:label="location_manager.text.sl_state"
            v-bind:hint="location_manager.text.triggers_geocode"
    ></v-text-field>
    <v-text-field
            name="zip"
            id="zip"
            v-model="location.sl_zip"
            v-bind:label="location_manager.text.sl_zip"
            v-bind:hint="location_manager.text.triggers_geocode"
    ></v-text-field>
    <v-text-field
            name="country"
            id="country"
            v-model="location.sl_country"
            v-bind:label="location_manager.text.sl_country"
            v-bind:hint="location_manager.text.triggers_geocode"
    ></v-text-field>
    <v-text-field
            name="latitude"
            id="latitude"
            data-field="sl_latitude"
            v-model="location.sl_latitude"
            v-bind:label="location_manager.text.sl_latitude"
            v-bind:hint="location_manager.text.latlng_placeholder"
    ></v-text-field>
    <v-text-field
            name="longitude"
            id="longitude"
            data-field="sl_longitude"
            v-model="location.sl_longitude"
            v-bind:label="location_manager.text.sl_longitude"
            v-bind:hint="location_manager.text.latlng_placeholder"
    ></v-text-field>
    <v-text-field
            name="description"
            id="description"
            v-model="location.sl_description"
            v-bind:label="location_manager.text.sl_description"
            multi-line
    ></v-text-field>
    <v-text-field
            name="url"
            id="url"
            v-model="location.sl_url"
            v-bind:label="location_manager.text.sl_url"
    ></v-text-field>
    <v-text-field
            name="email"
            id="email"
            v-model="location.sl_email"
            v-bind:label="location_manager.text.sl_email"
    ></v-text-field>
    <v-text-field
            name="hours"
            id="hours"
            v-model="location.sl_hours"
            v-bind:label="location_manager.text.sl_hours"
            multi-line
    ></v-text-field>
    <v-text-field
            name="phone"
            id="phone"
            v-model="location.sl_phone"
            v-bind:label="location_manager.text.sl_phone"
    ></v-text-field>
    <v-text-field
            name="fax"
            id="fax"
            v-model="location.sl_fax"
            v-bind:label="location_manager.text.sl_fax"
    ></v-text-field>
    <v-text-field
            name="image"
            id="image"
            v-model="location.sl_image"
            v-bind:label="location_manager.text.sl_image"
    ></v-text-field>
    <img v-bind:src="location.sl_image">
    <input
            type="checkbox"
            id="private"
            name="private"
            v-model="location.sl_private"
            true-value="1"
            false-value="0"
            v-bind:value="1"
    >
    <label for="private">{{location_manager.text.sl_private}}</label>

</template>
